name: Blendid Theme
version: "1.0"
description: Makes theming with a Blendid setup easier in Statamic
url: https://github.com/classyllama/blendid-theme-statamic-addon
developer: Kevin Kirchner
developer_url: https://www.classyllama.com
